### PR TITLE
Keep the jam going & other misc fixes

### LINKED ISSUE #542: Implants - Spawning always resets implant initialization
It should only reset when the player died. It should not reset when the player "redeployed" via deconstruct, IA, recall.

### LINKED ISSUE #813: Vehicles - Players randomly get stuck in Vehicles and Wall Turrets
Players randomly get stuck in Vehicles and Wall Turrets

### LINKED ISSUE #1017: Terminal condition glitched at NC base, Ikanam
Time of: *Monday, 5:49 PM CET*
In-game Location: *Ikanam / Amerish*
Factions: *Character is TR, base is NC*
<hr>

Upon REK engaging the vehicle terminal, the timer does not appear to start and the message is simply "Access Terminal." 

<a href="https://cdn.discordapp.com/attachments/295670273544290304/1069765184907911188/vehtermbugged.mp4">6 second video clip</a>

### LINKED ISSUE #1085: Vehicle wrecks appear on the minimap and have full health
wreck

https://github.com/psforever/PSF-LoginServer/assets/77748540/dee7f05c-0938-4169-93cd-8cc90122a2d5

It appears when you pull a new vehicle and it seems like the vehicle's previous owner has a higher chance of seeing the wreck like this, others don't always see its healthbar. For some reason this stuff doesn't show while on foot.

### LINKED ISSUE #1140: Can't get this game to work at all keep getting unknown connection error
image
Any help would be appreciated, but so far nothing works; setting launcher and game to run as admin had no effect. I get either "Unknown Connection Error" or "Unknown Login Error".

### LINKED ISSUE #1143: LLU location lost when player holding it disappears
When a player holding the LLU's session times out because of a crash or DC, the LLU is moved to 0 0 0 on the map.
I've looked at what happens with 2 LLUs at the same time and it appears they both go to 0 0 0, but because of a collision or some other reason, one or both of these LLUs will be physically gone even though it still shows them as being there on the map.

DudewheresmyLLU

Reproduction steps:
Hack an LLU base and grab the LLU.
Close the client with ALT + F4, or kill it with task manager.
Wait until the player's session times out.

### LINKED ISSUE #1145: Jam duration doesn't get extended
If you jam a vehicle, any additional EMP blasts are ignored by the jammed vehicle and they can only be rejammed after the initial jam ends.
This allows vehicles to get shots off inbetween jams, even though they should've been unable to.

### LINKED ISSUE #1150: Geowarps can crash players
Geowarps can make players crash. It doesn't always happen, but when it does it can be quite bad:

https://github.com/psforever/PSF-LoginServer/assets/77748540/5159cbbe-1e33-474e-aa7e-32ef7501b646

The respawn button doesn't work either.

### LINKED ISSUE #1153: LLU invisible to some after vehicle death
When a vehicle blows up with an LLU carrier inside it, only the former carrier can still see it. Other players that were near the death of the LLU carrier can not see the LLU anymore, that goes for the driver too.
Players that get onto the continent after the death of the LLU carrier can see it.

### PR DESCRIPTION
**Pull request by ScrawnyRonnie**
Fix #1145, resolves #1085, resolves #1150, resolves #1143, resolves #1153, resolves #542
Vehicle weapons and turrets should stay jammed if something jams them again.

Close other Issues that can be:
Fix #1017 
Fix #1140 
Fix #813

### CODE REVIEW

**Comment by ScrawnyRonnie** [comment]
While testing different ways to jam something I noticed the big bus EMP capacitor was recharging very quickly. Wiki says 20 minutes to full recharge, but this simply made it 10x longer than it was, so it takes 5 minutes now.

**Comment by Dethdeath** [comment]
Looks good.

**Comment by ScrawnyRonnie** [comment]
Caverns seem to have some kind of poisonous gas that selectively either allows players to explore them or will end their life upon entry. This isn't an ideal gaming experience, so a means to prevent random death upon zoning to a cavern has been introduced.

Some caverns seemed to be safer for entry (c1-3), but c4-6 had a higher chance at ending your life and causing a sad state for the client. This is to address and hopefully Fix #1150

**Comment by ScrawnyRonnie** [comment]
Fixed a few doors in Freyr on Esamir
Added a fix for #1143

**Comment by Dethdeath** [comment]
Freyr doors and #1143 are fixed. Came across #1153 during testing.

**Comment by ScrawnyRonnie** [comment]
cya #1153?
image

**Comment by ScrawnyRonnie** [comment]
This only fixes the issue if the LLU carrier dies after the driver in the kill feed. When the carrier shows up first, the LLU remains invisible.

**Comment by ScrawnyRonnie** [comment]
After more testing with LLU in a vehicle we found that sometimes this fix works and sometimes the LLU still becomes invisible. Investigating...

**Comment by ScrawnyRonnie** [comment]
Given the complexity of #1153 I'll just leave this as is. No additions coming to this PR.

**Comment by ScrawnyRonnie** [comment]
A few more additions:
The black screen in #1106 has been addressed in the change here in AvatarRejoin:
src/main/scala/net/psforever/actors/session/support/ZoningOperations.scala
Turns out unmounting and mounting the vehicle isn't required and from my testing you stay in the driver seat now and can continue to operate the vehicle. The other things in that issue are still present.

I noticed CancelZoningProcess was spamming constantly if a player was moving or firing a weapon. I added conditions for each so it only does this when a zoning request is actually being made (IA, recall, quit, etc). Will it reduce load in any capacity? idk

Also, when a zoning request is made it will now use DeactivateActiveImplants() instead of Deinitialize. This is in case the player moves or does something to cancel zoning so they can continue to use their implants. Deinitialize would completely disable them so they could not be used until zoning or dying.

**Comment by ScrawnyRonnie** [comment]
Had another go at #1153 thanks to an idea from @Resaec and it looks like it worked.

**Comment by Dethdeath** [comment]
Black screen seems fixed, so does #1153

**Comment by ScrawnyRonnie** [comment]
#542 is now part of this PR. Implants should now only deinitialize and fully restart the initialization timer after dying. Deconstructing and zoning via warpgate, IA, or recall should keep initialized implants in that state. Since each implant has a certain amount of time to "charge", a calculated time to initialize is set based on the time you last spawned (into the world or after dying). For example:
Enhanced Targeting has a 60 second initialization timer.
You died and respawned. The 60 second timer starts.
20 seconds later you deconstruct.
15 seconds later you spawn again after deconstructing.
Enhanced Targeting will initialize in 25 seconds based on the calculated timer that was set.

The character window where it shows the progress of initialization timers will reset each time if the implant was still under a timer and not initialized. It could be 10 seconds from initializing, but look like it just started if you just deconned. There doesn't appear to be a way to fix the visual progress bar there or make it start where it should be based on how much time is left, so it can go from looking like it barely started going to initialized white bar.

I've only come across one glitch so far with this change. Every now and then Surge would initialize even though it was nowhere near 90 seconds since its timer started. If I deconned or zoned again before that amount of time elapsed, sometimes it would stay initialized, other times it would not be and then initialize after the timer finished. Not sure why it would do this and it didn't happen with the other ones I tested. I guess the implant _surged_ to initialization? 😉

**Comment by Dethdeath** [comment]
Zoning does weird stuff to the timers. I see other implants like darklight also activate right after respawning. Somehow dying is being ignored.

**Comment by ScrawnyRonnie** [comment]
I think the timer issue is fixed now.

**Comment by Dethdeath** [comment]
I think so too.

**Pull request merged**
