### PR TITLE
First attempt at Docker file

### PR DESCRIPTION
**Pull request by adamlc**
Heres my first attempt at a Dockerfile (see #88), unfortunately I'm unable to test logging in at the moment but it appears to run without any errors etc. 

The sbt deps are downloaded in the build process, so everything should run instantly once the image is built. It may be worth doing an automated build on docker hub so everything stays up to date :)

### CODE REVIEW

**Comment by adamlc** [comment]
At some point I think ill borrow the dockerfile content from the upstream image so we can ensure we have the correct versions for things. At the moment the upstream uses the versions we need but it would be nice to specify them. Ill have a stab at that in the next few days! Going to dust off my windows pc this weekend to do some testing ;)

**Comment by pschord** [comment]
@adamlc Looks good. Can you download the repository ZIP instead of cloning? `https://github.com/psforever/PSF-LoginServer/archive/master.zip`

**Comment by adamlc** [comment]
@pschord sorry for the delay, all done :)

**Comment by pschord** [comment]
@adamlc This build doesn't appear to be working since the ZIP file change.
The `WORKDIR /PSF-LoginServer` line is being set incorrectly.

**Comment by adamlc** [comment]
Apologies @pschord, my fault for not testing! I did this time, its all good :)

**Comment by pschord** [comment]
Thanks!

**Pull request merged**
