### PR TITLE
Neutral Hotspots

### PR DESCRIPTION
**Pull request by Fate-JH**
Reduces combat. (It feels that way if you look at the map.)

### CODE REVIEW

**Comment by ScrawnyRonnie** [comment]
Hotspots appeared and disappeared for the involved empires. Did these tests:
- Neutral base turret and gen for the empire that damaged them
- Enemy base turret and gen for the owning empire and attacking empire
- Shooting an enemy character all good as well
The fireworks were fun while they lasted

**Comment by Dethdeath** [comment]
Tested this too for good measure, everything seems fine.

**Comment by ScrawnyRonnie** [comment]
For some reason the hotspot issue is back. Shooting a neutral turret doesn't make a hotspot again until you shoot an enemy owned one, then both and any additionally created ones are stuck forever.

**Comment by Dethdeath** [comment]
Can confirm, we did various tests last night. I shot all the wall turrets at 2 bases on Ceryshen (not neutral) and only 2 of these hotspots remained after like 5 minutes, they never went away after that. So it can be a pretty random result, which is why we thought it was fixed initially.

**Pull request merged**
