### PR TITLE
Fix vehicle inventory unloading on mounting

### PR DESCRIPTION
**Pull request by Mazo**
Yay, race conditions.

### CODE REVIEW

**Comment by ScrawnyRonnie** [comment]
Testing seemed to have just 1 minor bug. When I had either 1 ammo box or the maximum amount that would fit in the trunk, it caused the trunk's ammo to show as 1. Not sure if the amount of ammo per box matters for this. In my case the maximum I could fit was 1500 ammo. Firing once and reloading made it show the correct amount. Did the same thing for solo and passenger/gunner vehicles, but again a minor thing because the trunk never showed empty as it had before and fixes itself on reload.

**Comment by nwuollett** [comment]
@Mazo What's the status on this? Need more testing?

**Comment by NickPSF** [comment]
@Mazo What's the status on this? Need more testing?

**Comment by Mazo** [comment]
@NickPSF Not sure if the issue @ScrawnyRonnie mentioned is related or a completely different issue. I didn't come across it when I was testing, might be worth merging and raising as a separate issue if it continues?

**Comment by NickPSF** [comment]
@Mazo Seems fien to me!

**Pull request merged**
